---
title: "loc-temp"
author: "Rimjhim Saxena"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
rm(list = ls())
bat = read.csv("~/OneDrive - UCB-O365/CricketCC/Data/panel-player/batsmen.csv")
bowl = read.csv("~/OneDrive - UCB-O365/CricketCC/Data/panel-player/bowlers.csv")

loc = unique(bat$venue)
```



```{r}
for (i in 1:length(loc)) {
  filename = paste0("loc_",i)
  wd = paste0("~/OneDrive - UCB-O365/CricketCC/Data/loc-climate/clean/loc_",i,".csv")
  assign(filename,read.csv(wd))
}
```


```{r}
names = colnames(loc_1)
lst <- lapply(mget(paste0("loc_", 1:74)), setNames, names)
list2env(lst, envir = .GlobalEnv)
datasets = mget(paste0("loc_",1:74))
df = do.call("rbind", datasets)
colnames(df)[3] = "start_date"
```

```{r}
df$start_date = as.Date(df$start_date,"%m/%d/%y")
bat$start_date = as.Date(bat$start_date)
bowl$start_date = as.Date(bowl$start_date)

bat_loc = merge(bat,df,by=c("start_date","venue"))
bowl_loc = merge(bowl,df,by=c("start_date","venue"))

write.csv(bat_loc,"~/OneDrive - UCB-O365/CricketCC/Data/final/bat_loc.csv",row.names = F)
write.csv(bowl_loc,"~/OneDrive - UCB-O365/CricketCC/Data/final/bowl_loc.csv",row.names = F)
```
