---
title: "wcbat-games"
author: "Rimjhim Saxena"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
rm(list = ls())
bat = read.csv("~/OneDrive - UCB-O365/CricketCC/Data/final/bat_loc.csv")
bowl = read.csv("~/OneDrive - UCB-O365/CricketCC/Data/final/bowl_loc.csv")
```

```{r}
lastgame_prewc_bat = bat %>% 
  group_by(striker) %>%
  slice(which.max(as.Date(start_date)))

```


```{r}
wc = read.csv("~/OneDrive - UCB-O365/CricketCC/Data/worldcup-games/wcgames.csv")
wc_teams = c("Namibia","Sri Lanka","Netherlands","United Arab Emirates","Scotland","West Indies","Ireland","Zimbabwe","New Zealand","England","Australia","Afghanistan","India","Pakistan","South Africa","Bangladesh")
wc = wc[which(wc$batting_team %in% wc_teams),]
wc_loc = as.data.frame(table(wc$venue))
write.csv(wc_loc,"~/OneDrive - UCB-O365/CricketCC/Data/location_wc.csv",row.names = F)
wc_loc = unique(wc$venue)
sample = wc[which(wc$venue %in% wc_loc[1]),]
```


```{r}
for (i in 1:length(wc_loc)) {
  filename = paste0("loc_",i)
  wd = paste0("~/OneDrive - UCB-O365/CricketCC/Data/loc-climate/wc-games/loc_",i,".csv")
  assign(filename,read.csv(wd))
}

datasets = mget(paste0("loc_",1:7))
df = do.call("rbind", datasets)
colnames(df)[3] = "start_date"
df$start_date = as.Date(df$start_date,"%m/%d/%y")
write.csv(df,"~/OneDrive - UCB-O365/CricketCC/Data/loc-climate/wcgame_temp.csv",row.names = F)
```


```{r}
wc_bat = read.csv("~/OneDrive - UCB-O365/CricketCC/Data/panel-player/wc_bat.csv")
wc_bowl = read.csv("~/OneDrive - UCB-O365/CricketCC/Data/panel-player/wc_bowl.csv")
wc_bat$start_date = as.Date(wc_bat$start_date)
wc_bowl$start_date = as.Date(wc_bowl$start_date)
wcbat_loc = merge(wc_bat,df,by=c("start_date","venue"))
wcbowl_loc = merge(wc_bowl,df,by=c("start_date","venue"))
write.csv(wcbat_loc,"~/OneDrive - UCB-O365/CricketCC/Data/final/wcbat_loc.csv",row.names = F)
write.csv(wcbowl_loc,"~/OneDrive - UCB-O365/CricketCC/Data/final/wcbowl_loc.csv",row.names = F)
```








