---
title: "12distance-bw-points"
author: "Rimjhim Saxena"
date: "`r Sys.Date()`"
output: html_document
---
```{r}
rm(list = ls())
home = read.csv("~/OneDrive - UCB-O365/CricketCC/Data/home/batsmen-loc.csv")
clim = read.csv("~/OneDrive - UCB-O365/CricketCC/Data/loc-climate/monthly-all.csv")
```


```{r}
library(sf)
library(tidyverse)
home = home %>% 
  separate(loc,c("lat","lon"),",")
clim$lon_new = ifelse(clim$lon<=180,clim$lon,clim$lon-360)
```

```{r}
library(raster)
names(clim)
climate = clim[,c(7,2)]
names(climate) = c("lon","lat")
loc = home[,c(3,2)]

climate = as.matrix(climate)
loc$lon = as.numeric(loc$lon)
loc$lat = as.numeric(loc$lat)

names(home) = c("batsmen","home_lat","home_lon")
```

```{r}

df = data.frame(matrix(nrow = 0,ncol = 11))
names(df) = c("V1","lon","lat","date","airtemp","precip","humidity","lon_new","batsmen","home_lat","home_lon")

n = nrow(loc)
xy <- vector("list", n)

for (i in 1:161) {
  distance = spDists(climate,loc[i,])
  distance = as.data.frame(distance)
distance = cbind(distance,clim)
distance = cbind(distance,home[i,])
xy[[i]] = distance %>% 
  slice_min(V1)
}

xy <- do.call(rbind, xy)





```


```{r}
distance = spDists(climate,loc[160,])
distance = as.data.frame(distance)
distance = cbind(distance,clim)
distance = cbind(distance,home[160,])
slice = distance %>% 
  slice_min(V1)

xy = rbind(xy,slice)

write.csv(xy,"~/OneDrive - UCB-O365/CricketCC/Data/home/batsmen-clim-loc.csv",row.names = F)
```
