---
title: "28regs"
author: "Rimjhim Saxena"
date: '2023-02-26'
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls())
options(scipen=999)


bat = read.csv("~/OneDrive - UCB-O365/CricketCC/Data/final/batsmen.csv")  
bowl = read.csv("~/OneDrive - UCB-O365/CricketCC/Data/final/bowler.csv")

library(lubridate)
library(tidyverse)
library(fixest)

bat$start_date = as.Date(bat$start_date)
bowl$start_date = as.Date(bowl$start_date)

bat_alt = bat %>% 
  arrange(start_date) %>% 
  group_by(striker) %>% 
  mutate(change_temp = tempmax - lag(tempmax),
          home_change = tempmax - home_airtemp,
         gap_days = c(NA,diff(start_date)))

bowl_alt = bowl %>% 
  arrange(start_date) %>% 
  group_by(bowler) %>% 
  mutate(change_temp = tempmax - lag(tempmax),
         home_change = tempmax - home_airtemp,
         gap_days = c(NA,diff(start_date)))


bat_alt$heat = ifelse(bat_alt$home_change<0,0,bat_alt$home_change)
bowl_alt$heat = ifelse(bowl_alt$home_change<0,0,bowl_alt$home_change)

bat_alt = bat_alt %>% 
  arrange(start_date) %>% 
  group_by(striker) %>% 
  mutate(accum = cumsum(heat))

bowl_alt = bowl_alt %>% 
  arrange(start_date) %>% 
  group_by(bowler) %>% 
  mutate(accum = cumsum(heat))


bat_alt = bat_alt[,c(1:17,23,24,47:54)]
bowl_alt = bowl_alt[,c(1:20,26,27,50:57)]

# Dummies - Batsmen
bat_alt$accbin = cut(bat_alt$accum, breaks = c(0,100,Inf),include.lowest = T)
bat_alt$gapbin = cut(bat_alt$gap_days, breaks = c(0,3,14,Inf),include.lowest = T)
bat_alt$tempbin = cut(bat_alt$change_temp, breaks = c(-Inf,-2,2,Inf))

# Creating interaction - Batsmen
bat_alt$interact_home <- interaction(bat_alt$accbin, bat_alt$gapbin)
bat_alt$interact_home = relevel(bat_alt$interact_home,ref = "(100,Inf].(3,14]")

bat_alt$interact_var <- interaction(bat_alt$tempbin, bat_alt$gapbin)
bat_alt$interact_var = relevel(bat_alt$interact_var,ref = "(-2,2].[0,3]")

# Dummies - Bowlers
bowl_alt$accbin = cut(bowl_alt$accum, breaks = c(0,100,Inf),include.lowest = T)
bowl_alt$gapbin = cut(bowl_alt$gap_days, breaks = c(0,3,14,Inf),include.lowest = T)
bowl_alt$tempbin = cut(bowl_alt$change_temp, breaks = c(-Inf,-2,2,Inf))

# Creating interaction - Bowlers
bowl_alt$interact_home <- interaction(bowl_alt$accbin, bowl_alt$gapbin)
bowl_alt$interact_home = relevel(bowl_alt$interact_home,ref = "(100,Inf].(3,14]")

bowl_alt$interact_var <- interaction(bowl_alt$tempbin, bowl_alt$gapbin)
bowl_alt$interact_var = relevel(bowl_alt$interact_var,ref = "(-2,2].[0,3]")

# Excessive Temp shock 
bat_alt$tempshock = bat_alt$tempmax - 25
bat_alt$shock = ifelse(bat_alt$tempshock>0,1,0)

bat_alt$interact_shock <- interaction(bat_alt$shock, bat_alt$gapbin)
bat_alt$interact_shock = relevel(bat_alt$interact_shock,ref = "0.(14,Inf]")


bowl_alt$tempshock = bowl_alt$tempmax - 25
bowl_alt$shock = ifelse(bowl_alt$tempshock>0,1,0)

bowl_alt$interact_shock <- interaction(bowl_alt$shock, bowl_alt$gapbin)
bowl_alt$interact_shock = relevel(bowl_alt$interact_shock,ref = "0.(14,Inf]")

```



```{r}
summary(bat_alt$gap_days)
test_bat = bat_alt[which(bat_alt$gap_days<=3),]
test_bat$batshock = ifelse(test_bat$change_temp>0,1,0)

```

```{r}
reg1 = feols(runs ~ batshock + precip + humidity|batting_order + match_id,data = test_bat)
reg2 = feols(boundary ~ batshock + precip + humidity|batting_order,data = test_bat)
reg3 = feols(balls ~ batshock + precip + humidity|batting_order,data = test_bat)

summary(reg2)

```



# Temperature Shock

```{r echo=FALSE,include=FALSE}
reg1 = feols(runs ~ interact_var + precip + humidity + opp_team_temp|batting_team + batting_order + innings,data = bat_alt,cluster = c("striker"))
reg2 = feols(balls ~ interact_var + precip + humidity + opp_team_temp|batting_team + batting_order + innings,data = bat_alt,cluster = c("striker"))
reg3 = feols(strike_rate ~ interact_var + precip + humidity + opp_team_temp|batting_team + batting_order + innings,data = bat_alt,cluster = c("striker"))
reg4 = feols(boundary ~ interact_var + precip + humidity + opp_team_temp|batting_team + batting_order + innings,data = bat_alt,cluster = c("striker"))

regs = list("runs" = reg1,"balls" = reg2,"strike rate" = reg3,"boundary" = reg4)

library(modelsummary)
library(kableExtra)
library(pander)

fn <- "Standard Errors clustered at Batsmen level."

tab_1 <- modelsummary(regs,
                      stars = TRUE,
                      title = "Effect of temperature shocks on Batsmen productivity",
                      gof_omit = "R2 Within|R2 P|Log|AIC|BIC|Std",
                      output = "markdown",
                      escape = FALSE,
                      fmt = "%.4f")
```
